### ISSUE TITLE
"errors":"'enable_emphasis'"

### ISSUE THREAD

**Issue by tornado909** [zijiren233/Stable-Diffusion-Webui-Bot#7]
https://github.com/zijiren233/Stable-Diffusion-Webui-Bot/blob/b715f7e1eda62c044aa62d08d81bced308de0ff9/stable-diffusion-webui-api/failover.go#L68

При попытке создания изображения:
Draw Err [ascento] : change option err: {"error":"KeyError","detail":"","body":"","errors":"'enable_emphasis'"}

В SD:
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/options {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "'enable_emphasis'"}
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-1.8.0\modules\api\api.py", line 186, in exception_handling
        return await call_next(request)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "D:\stable-diffusion-webui-1.8.0\modules\api\api.py", line 150, in log_and_time
        res: Response = await call_next(req)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "D:\stable-diffusion-webui-1.8.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "D:\stable-diffusion-webui-1.8.0\modules\api\api.py", line 675, in set_config
        shared.opts.set(k, v, is_api=True)
      File "D:\stable-diffusion-webui-1.8.0\modules\options.py", line 151, in set
        option = self.data_labels[key]
    KeyError: 'enable_emphasis'

---

**Comment by Ivan12341241** [comment]
"enable_emphasis": true" delete and build new
